# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/main_window_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.playlist_widget = QtWidgets.QWidget(self.centralwidget)
        self.playlist_widget.setGeometry(QtCore.QRect(10, 10, 800, 800))
        self.playlist_widget.setObjectName("playlist_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.playlist_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.playlist_view_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.playlist_view_layout.setContentsMargins(0, 0, 0, 0)
        self.playlist_view_layout.setObjectName("playlist_view_layout")
        self.playlist = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.playlist.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playlist.setFrameShape(QtWidgets.QFrame.Box)
        self.playlist.setObjectName("playlist")
        self.playlist_view_layout.addWidget(self.playlist)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.delete_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_btn.sizePolicy().hasHeightForWidth())
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.delete_btn.setAutoFillBackground(False)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.playlist_view_layout.addLayout(self.horizontalLayout)
        self.import_btn = QtWidgets.QPushButton(self.centralwidget)
        self.import_btn.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.import_btn.setText("")
        self.import_btn.setObjectName("import_btn")
        self.style_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_1.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_1.setText("")
        self.style_btn_1.setObjectName("style_btn_1")
        self.style_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_2.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_2.setText("")
        self.style_btn_2.setObjectName("style_btn_2")
        self.style_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_3.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_3.setText("")
        self.style_btn_3.setObjectName("style_btn_3")
        self.style_btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_4.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_4.setText("")
        self.style_btn_4.setObjectName("style_btn_4")
        self.style_btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_5.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_5.setText("")
        self.style_btn_5.setObjectName("style_btn_5")
        self.style_btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_6.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_6.setText("")
        self.style_btn_6.setObjectName("style_btn_6")
        self.style_btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_7.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_7.setText("")
        self.style_btn_7.setObjectName("style_btn_7")
        self.style_btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.style_btn_8.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.style_btn_8.setText("")
        self.style_btn_8.setObjectName("style_btn_8")
        self.play_pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause_btn.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.play_pause_btn.setText("")
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.rotate_note_label = QtWidgets.QLabel(self.centralwidget)
        self.rotate_note_label.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.rotate_note_label.setText("")
        self.rotate_note_label.setObjectName("rotate_note_label")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.background_label.setText("")
        self.background_label.setObjectName("background_label")
        self.background_label.raise_()
        self.rotate_note_label.raise_()
        self.playlist_widget.raise_()
        self.import_btn.raise_()
        self.style_btn_2.raise_()
        self.style_btn_3.raise_()
        self.style_btn_4.raise_()
        self.style_btn_5.raise_()
        self.style_btn_6.raise_()
        self.style_btn_7.raise_()
        self.style_btn_8.raise_()
        self.style_btn_1.raise_()
        self.play_pause_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.back_btn.setText(_translate("MainWindow", "返回"))
        self.delete_btn.setText(_translate("MainWindow", "删除"))


